default:
    extension: .icls
    output: colors

theme:
    extension: .theme.xml
    output: build

accent:
    extension: .accent.xml
    output: build

scheme:
    extension: .scheme.xml
    output: build
